#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

readonly SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
readonly REPO_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

usage() {
  cat <<'USAGE'
Usage:
  ./scripts/run-nixos-anywhere.sh --disk /dev/vda --confirm-destroy /dev/vda --hostname arch-host --target root@host [options]

Options:
  --disk PATH                Target disk (required)
  --confirm-destroy PATH     Must exactly match --disk (required)
  --hostname NAME            Hostname (required)
  --target USER@HOST         SSH target for nixos-anywhere (required)
  --username NAME            Primary username (default: k)
  --timezone TZ              Timezone (default: America/Chicago)
  --root-password-file PATH  Root password file (required)
  --user-password-file PATH  User password file (required)
  --luks-password-file PATH  LUKS passphrase file (required)
  --disable-tpm-enroll       Skip TPM enrollment (default: enabled)
  --dry-run                  Print resolved command and generated paths, then exit
  --help                     Show help
USAGE
}

log() {
  printf '[nixos-anywhere] %s\n' "$*"
}

die() {
  printf '[nixos-anywhere] ERROR: %s\n' "$*" >&2
  exit 1
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "Missing command: $1"
}

partition_path() {
  local disk="$1"
  local index="$2"
  if [[ "$disk" =~ ^/dev/(nvme|mmcblk) ]]; then
    printf '%sp%s' "$disk" "$index"
  else
    printf '%s%s' "$disk" "$index"
  fi
}

hash_password() {
  local plaintext="$1"

  if command -v mkpasswd >/dev/null 2>&1; then
    mkpasswd -m sha-512 "$plaintext"
    return 0
  fi

  if command -v openssl >/dev/null 2>&1; then
    openssl passwd -6 "$plaintext"
    return 0
  fi

  die "Need either mkpasswd (whois) or openssl to hash passwords"
}

DISK=""
CONFIRM_DESTROY=""
HOSTNAME=""
TARGET=""
USERNAME="k"
TIMEZONE="America/Chicago"
ROOT_PASSWORD_FILE=""
USER_PASSWORD_FILE=""
LUKS_PASSWORD_FILE=""
ENABLE_TPM_ENROLL="true"
DRY_RUN=0

while (($# > 0)); do
  case "$1" in
    --disk)
      DISK="${2:-}"
      shift 2
      ;;
    --confirm-destroy)
      CONFIRM_DESTROY="${2:-}"
      shift 2
      ;;
    --hostname)
      HOSTNAME="${2:-}"
      shift 2
      ;;
    --target)
      TARGET="${2:-}"
      shift 2
      ;;
    --username)
      USERNAME="${2:-}"
      shift 2
      ;;
    --timezone)
      TIMEZONE="${2:-}"
      shift 2
      ;;
    --root-password-file)
      ROOT_PASSWORD_FILE="${2:-}"
      shift 2
      ;;
    --user-password-file)
      USER_PASSWORD_FILE="${2:-}"
      shift 2
      ;;
    --luks-password-file)
      LUKS_PASSWORD_FILE="${2:-}"
      shift 2
      ;;
    --disable-tpm-enroll)
      ENABLE_TPM_ENROLL="false"
      shift
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      die "Unknown argument: $1"
      ;;
  esac
done

[[ -n "$DISK" ]] || die "--disk is required"
[[ -n "$CONFIRM_DESTROY" ]] || die "--confirm-destroy is required"
[[ -n "$HOSTNAME" ]] || die "--hostname is required"
[[ -n "$TARGET" ]] || die "--target is required"
[[ -n "$ROOT_PASSWORD_FILE" ]] || die "--root-password-file is required"
[[ -n "$USER_PASSWORD_FILE" ]] || die "--user-password-file is required"
[[ -n "$LUKS_PASSWORD_FILE" ]] || die "--luks-password-file is required"

[[ "$CONFIRM_DESTROY" == "$DISK" ]] || die "--confirm-destroy must match --disk"
[[ -b "$DISK" ]] || die "Disk not found: $DISK"
[[ -f "$ROOT_PASSWORD_FILE" ]] || die "Root password file not found"
[[ -f "$USER_PASSWORD_FILE" ]] || die "User password file not found"
[[ -f "$LUKS_PASSWORD_FILE" ]] || die "LUKS password file not found"

ROOT_PASSWORD="$(<"$ROOT_PASSWORD_FILE")"
USER_PASSWORD="$(<"$USER_PASSWORD_FILE")"
LUKS_PASSWORD="$(<"$LUKS_PASSWORD_FILE")"

[[ -n "$ROOT_PASSWORD" ]] || die "Root password file is empty"
[[ -n "$USER_PASSWORD" ]] || die "User password file is empty"
[[ -n "$LUKS_PASSWORD" ]] || die "LUKS password file is empty"

require_cmd nix

ROOT_HASH="$(hash_password "$ROOT_PASSWORD")"
USER_HASH="$(hash_password "$USER_PASSWORD")"
LUKS_PARTITION="$(partition_path "$DISK" 2)"

TMP_DIR="$(mktemp -d /tmp/nixos-anywhere.XXXXXX)"
EXTRA_FILES_DIR="${TMP_DIR}/extra-files"
FLAKE_DIR="${TMP_DIR}/flake"

cleanup() {
  rm -rf "$TMP_DIR"
}
trap cleanup EXIT

mkdir -p "$EXTRA_FILES_DIR/var/lib/install" "$FLAKE_DIR"

# Keep evaluation pure by staging local modules into the ephemeral flake.
cp -a "${REPO_ROOT}/hosts" "${FLAKE_DIR}/hosts"
cp -a "${REPO_ROOT}/modules" "${FLAKE_DIR}/modules"

printf '%s' "$LUKS_PARTITION" > "$EXTRA_FILES_DIR/var/lib/install/luks-partition"
printf '%s' "$LUKS_PASSWORD" > "$EXTRA_FILES_DIR/var/lib/install/luks-passphrase"
chmod 600 "$EXTRA_FILES_DIR/var/lib/install/luks-partition" "$EXTRA_FILES_DIR/var/lib/install/luks-passphrase"

cat >"${FLAKE_DIR}/flake.nix" <<EOF_FLAKE
{
  description = "Ephemeral install flake generated by run-nixos-anywhere.sh";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    disko.url = "github:nix-community/disko";
    disko.inputs.nixpkgs.follows = "nixpkgs";
  };

  outputs = { self, nixpkgs, disko, ... }:
  let
    system = "x86_64-linux";
    lib = nixpkgs.lib;
  in {
    nixosConfigurations.${HOSTNAME} = lib.nixosSystem {
      inherit system;
      modules = [
        disko.nixosModules.disko
        ./hosts/arch-host/default.nix
        {
          networking.hostName = "${HOSTNAME}";

          install.username = "${USERNAME}";
          install.timezone = "${TIMEZONE}";
          install.enableTpmEnroll = ${ENABLE_TPM_ENROLL};
          install.vmTestAutoUnlock = false;
          install.diskDevice = "${DISK}";
          install.rootLvSize = "80G";
          install.homeLvSize = "100%FREE";
          install.luksPasswordFile = "/tmp/luks-passphrase";

          users.users.root.hashedPassword = "${ROOT_HASH}";
          users.users.${USERNAME}.hashedPassword = "${USER_HASH}";
        }
      ];
    };
  };
}
EOF_FLAKE

NIXOS_ANYWHERE_CMD=(
  nix
  --extra-experimental-features
  "nix-command flakes"
  run
  github:nix-community/nixos-anywhere
  --
  --flake "${FLAKE_DIR}#${HOSTNAME}"
  --disk-encryption-keys "/tmp/luks-passphrase" "$LUKS_PASSWORD_FILE"
  --extra-files "$EXTRA_FILES_DIR"
  "$TARGET"
)

if [[ "$DRY_RUN" -eq 1 ]]; then
  log "Dry run enabled"
  log "Generated flake: ${FLAKE_DIR}/flake.nix"
  log "Generated extra files: ${EXTRA_FILES_DIR}"
  printf '%q ' "${NIXOS_ANYWHERE_CMD[@]}"
  printf '\n'
  exit 0
fi

log "Starting unattended install for host ${HOSTNAME} on ${TARGET}"
printf '[nixos-anywhere] Command: '
printf '%q ' "${NIXOS_ANYWHERE_CMD[@]}"
printf '\n'
"${NIXOS_ANYWHERE_CMD[@]}"
